=== theoportlock/proteintools/database/Taminoaciddata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Taminoaciddata" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Taminoaciddata">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="ZGcpyqlYjkuhXY7BSDU32g==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABkZynKqViOS6FdjsFINTfaAAAAAAgM9SW4FOVAAAAAAAAAAABUAEEA
YQBtAGkAbgBvAGEAYwBpAGQAZABhAHQAYQAAAAAAAADVrxC9zxzqRLPkezTnZmfJ
BwAAAGRnKcqpWI5LoV2OwUg1N9pJAEQAAAAAAAAA+lRo2Cp0kkWkg3I841gOOgcA
AABkZynKqViOS6FdjsFINTfaQQBBAAAAAAAAAMLSdDf5tptPij0xwya002oHAAAA
ZGcpyqlYjkuhXY7BSDU32k0AVwAAAAAAAABcVstcXMxdQYX/CpxlYWhYBwAAAGRn
KcqpWI5LoV2OwUg1N9pFAFgAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="1a8Qvc8c6kSz5Hs052ZnyQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AA" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="+lRo2Cp0kkWkg3I841gOOg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MW" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="wtJ0N/m2m0+KPTHDJrTTag==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EXT" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="XFbLXFzMXUGF/wqcZWFoWA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== theoportlock/proteintools/database/Taminoaciddata.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Taminoaciddata.xsd" generated="2020-01-12T15:39:32">
<Taminoaciddata>
<ID>1</ID>
<AA>A</AA>
<MW>213</MW>
<EXT>213</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>2</ID>
<AA>B</AA>
<MW>310</MW>
<EXT>310</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>3</ID>
<AA>C</AA>
<MW>156</MW>
<EXT>156</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>4</ID>
<AA>D</AA>
<MW>243</MW>
<EXT>243</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>5</ID>
<AA>E</AA>
<MW>21</MW>
<EXT>21</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>6</ID>
<AA>F</AA>
<MW>654</MW>
<EXT>654</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>7</ID>
<AA>G</AA>
<MW>213</MW>
<EXT>213</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>8</ID>
<AA>H</AA>
<MW>168</MW>
<EXT>168</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>9</ID>
<AA>I</AA>
<MW>432</MW>
<EXT>432</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>10</ID>
<AA>J</AA>
<MW>879</MW>
<EXT>879</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>11</ID>
<AA>K</AA>
<MW>549</MW>
<EXT>549</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>12</ID>
<AA>L</AA>
<MW>679</MW>
<EXT>679</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>13</ID>
<AA>M</AA>
<MW>126</MW>
<EXT>126</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>14</ID>
<AA>N</AA>
<MW>121</MW>
<EXT>121</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>15</ID>
<AA>O</AA>
<MW>333</MW>
<EXT>333</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>16</ID>
<AA>P</AA>
<MW>515</MW>
<EXT>515</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>17</ID>
<AA>Q</AA>
<MW>132</MW>
<EXT>132</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>18</ID>
<AA>R</AA>
<MW>134</MW>
<EXT>134</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>19</ID>
<AA>S</AA>
<MW>564</MW>
<EXT>564</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>20</ID>
<AA>T</AA>
<MW>556</MW>
<EXT>556</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>21</ID>
<AA>U</AA>
<MW>489</MW>
<EXT>489</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>22</ID>
<AA>V</AA>
<MW>797</MW>
<EXT>797</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>23</ID>
<AA>W</AA>
<MW>654</MW>
<EXT>654</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>24</ID>
<AA>X</AA>
<MW>437</MW>
<EXT>437</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>25</ID>
<AA>Y</AA>
<MW>767</MW>
<EXT>767</EXT>
</Taminoaciddata>
<Taminoaciddata>
<ID>26</ID>
<AA>Z</AA>
<MW>0</MW>
<EXT>0</EXT>
</Taminoaciddata>
</dataroot>
