=== theoportlock/proteintools/database/Tgrow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Tgrow" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Tgrow">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="Purification Log ID" index-key="Purification_x0020_Log_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="TpurificationlogTgrow" index-key="Purification_x0020_Log_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABLiin/iTR0TZAEzxgWRiF4AAAAAL4KtPS2WuVAAAAAAAAAAABUAGcA
cgBvAHcAAAAAAAAABrEouvLegUWDJYs7IwE21gcAAABLiin/iTR0TZAEzxgWRiF4
SQBEAAAAAAAAANgJBIDaKrBPrR9eZjEn8vgHAAAAS4op/4k0dE2QBM8YFkYheFAA
dQByAGkAZgBpAGMAYQB0AGkAbwBuACAATABvAGcAIABJAEQAAAAAAAAAawMyef2X
Wki1C2xvBxuvkAcAAABLiin/iTR0TZAEzxgWRiF4VABpAG0AZQAgACgAbQBpAG4A
KQAAAAAAAAAu9CN6Vx3GRY//lcy2BPnUBwAAAEuKKf+JNHRNkATPGBZGIXhPAEQA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="S4op/4k0dE2QBM8YFkYheA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="BrEouvLegUWDJYs7IwE21g==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Purification_x0020_Log_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="2AkEgNoqsE+tH15mMSfy+A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2220"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Time_x0020__x0028_min_x0029_" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="awMyef2XWki1C2xvBxuvkA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1995"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="OD" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="LvQjelcdxkWP/5XMtgT51A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== theoportlock/proteintools/database/Tgrow.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Tgrow.xsd" generated="2020-01-12T15:43:48">
<Tgrow>
<ID>1</ID>
<Purification_x0020_Log_x0020_ID>3</Purification_x0020_Log_x0020_ID>
<Time_x0020__x0028_min_x0029_>0</Time_x0020__x0028_min_x0029_>
<OD>0</OD>
</Tgrow>
<Tgrow>
<ID>2</ID>
<Purification_x0020_Log_x0020_ID>3</Purification_x0020_Log_x0020_ID>
<Time_x0020__x0028_min_x0029_>1</Time_x0020__x0028_min_x0029_>
<OD>0</OD>
</Tgrow>
<Tgrow>
<ID>3</ID>
<Purification_x0020_Log_x0020_ID>3</Purification_x0020_Log_x0020_ID>
<Time_x0020__x0028_min_x0029_>2</Time_x0020__x0028_min_x0029_>
<OD>0</OD>
</Tgrow>
<Tgrow>
<ID>4</ID>
<Purification_x0020_Log_x0020_ID>3</Purification_x0020_Log_x0020_ID>
<Time_x0020__x0028_min_x0029_>3</Time_x0020__x0028_min_x0029_>
<OD>1</OD>
</Tgrow>
<Tgrow>
<ID>5</ID>
<Purification_x0020_Log_x0020_ID>3</Purification_x0020_Log_x0020_ID>
<Time_x0020__x0028_min_x0029_>4</Time_x0020__x0028_min_x0029_>
<OD>1</OD>
</Tgrow>
</dataroot>
