=== theoportlock/proteintools/database/Tproteindata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Tproteindata" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Tproteindata">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="AA num" index-key="AA_x0020_num " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Plasmid" index-key="Plasmid " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACU7+iPFLttQ6fNczufO5jCAAAAAI5Zk7VzFeVAAAAAAAAAAABUAHAA
cgBvAHQAZQBpAG4AZABhAHQAYQAAAAAAAADwkvPGtjy1S6BqOxNuilBtAAAAALYE
t2FzFeVAAAAAAAAAAABUAHAAdQByAGkAZgBpAGMAYQB0AGkAbwBuAGwAbwBnAAAA
AAAAAK20UdoWlsZOgNK5lkGWmzEHAAAAlO/ojxS7bUOnzXM7nzuYwkkARAAAAAAA
AABbGWg8sLH+QJcWOm2O9BnbBwAAAJTv6I8Uu21Dp81zO587mMJQAHIAbwB0AE4A
YQBtAGUAAAAAAAAA88mLGgT+SEyTx4XO9ek9EAcAAACU7+iPFLttQ6fNczufO5jC
RQBYAFQAAAAAAAAA1jB362RgsUG/p/cqtysQpQcAAACU7+iPFLttQ6fNczufO5jC
TQBXACAAKABEAGEAKQAAAAAAAABA8aTx5fTnSogcXs8OakOSBwAAAJTv6I8Uu21D
p81zO587mMJQAGwAYQBzAG0AaQBkAAAAAAAAAN3rYeuZRN5NqJfoml9eeKcHAAAA
lO/ojxS7bUOnzXM7nzuYwlAAbABhAHMAbQBpAGQAIABSAGUAcwBpAHMAdABhAG4A
YwBlAAAAAAAAAIWMIDq9vuhMkseW9zlZfBMHAAAAlO/ojxS7bUOnzXM7nzuYwkEA
QQAgAHMAZQBxAAAAAAAAAOfSqxFFzbRPtCfmitL3LVYHAAAAlO/ojxS7bUOnzXM7
nzuYwkEAQQAgAG4AdQBtAAAAAAAAAAIIUUXZGbtEuJdrBBHz4FsHAAAAlO/ojxS7
bUOnzXM7nzuYwkgAeQBkAHIAbwBwAGgAbwBiAGkAYwBpAHQAeQAAAAAAAADPc/wL
i7kVT64j3eHW2mfCBwAAAJTv6I8Uu21Dp81zO587mMJBAGwAaQBwAGgAYQB0AGkA
YwBzAAAAAAAAAFrgPqzLEoBAh2LnRQCvVOQHAAAAlO/ojxS7bUOnzXM7nzuYwkkA
bgBzAHQAYQBiAGkAbABpAHQAeQAAAAAAAABcX6waWcL4S68oMnni4JDgBwAAAJTv
6I8Uu21Dp81zO587mMJQAGkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAA
AAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="lO/ojxS7bUOnzXM7nzuYwg==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="rbRR2haWxk6A0rmWQZabMQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ProtName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="WxloPLCx/kCXFjptjvQZ2w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="EXT" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="88mLGgT+SEyTx4XO9ek9EA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MW_x0020__x0028_Da_x0029_" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="1jB362RgsUG/p/cqtysQpQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Plasmid" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="QPGk8eX050qIHF7PDmpDkg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Plasmid_x0020_Resistance" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="3eth65lE3k2ol+iaX154pw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AA_x0020_seq" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="hYwgOr2+6EySx5b3OVl8Ew==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AA_x0020_num" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="59KrEUXNtE+0J+aK0vctVg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Hydrophobicity" minOccurs="0" od:jetType="single" od:sqlSType="real" type="xsd:float">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="AghRRdkZu0S4l2sEEfPgWw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="2"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Aliphatics" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="z3P8C4u5FU+uI93h1tpnwg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Instability" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="WuA+rMsSgECHYudFAK9U5A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Pi" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="XF+sGlnC+EuvKDJ54uCQ4A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="2"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== theoportlock/proteintools/database/Tproteindata.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Tproteindata.xsd" generated="2020-01-12T15:44:29">
<Tproteindata>
<ID>1</ID>
<ProtName>02811</ProtName>
<EXT>33935</EXT>
<MW_x0020__x0028_Da_x0029_>33157</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMNSDDNADGLIFSPLPQNKNTVVRHYSNEQEMPNLSQMAQRTIDFPTQIVRVSGNLTGLELSCDDVENEIDQVFSKKISPNLFTYNTYVSCGYDVNDPEQHATNFSIQSYFDPLTDNAVDYLKSYLKEYNGYNLFNTTTLQIENAKGIIVSMNLNAGLKSNPDKTPFTLYRQDRNNFYFKSNFDVRKELISDIYQRFYSNDPDMILPFFDKWIFSYAGSVYYSILMASNYLELQPERIFVMENEGDIFVSDLRYYFANLCMKRNPNKHCL</AA_x0020_seq>
<AA_x0020_num>284</AA_x0020_num>
<Hydrophobicity>-0.576</Hydrophobicity>
<Aliphatics>72</Aliphatics>
<Instability>39</Instability>
<Pi>5</Pi>
</Tproteindata>
<Tproteindata>
<ID>2</ID>
<ProtName>10421</ProtName>
<EXT>46388</EXT>
<MW_x0020__x0028_Da_x0029_>44247</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMFTLPRQPTKSYECENCSQLSRENLHDKWEITNEPLNNNISNVRRSYGYKERISLEQLQRGVIISTLAPGAVVRITPLQNKSIPELLIKTPKNQLLPLKEASSLYNQDDEVGNNPLAITKHQAMLQIKPELGYGKFILKSKDITNKYADAYMISVLDKFSITYLEVETDSLHYQYGDKLKATISLHNDITEYDVNDVDARLVGPKGQVISLNLTKLKSNVFEGTATLDSELNDRGENWYLETDVQTEYGQEIIRRSGHTAFSYSIPSASLMNVKKLSSKPLTFVVTVDVATASRYALQSVLFQKNGKGEARPIQTSQRAQWLEPGKHVLQFTFDNHNQLSDDNLYLGYLRLIDYGQLKTVYQYNQPVKLSQLVD</AA_x0020_seq>
<AA_x0020_num>388</AA_x0020_num>
<Hydrophobicity>-0.551</Hydrophobicity>
<Aliphatics>90</Aliphatics>
<Instability>32</Instability>
<Pi>6</Pi>
</Tproteindata>
<Tproteindata>
<ID>3</ID>
<ProtName>13951</ProtName>
<EXT>14105</EXT>
<MW_x0020__x0028_Da_x0029_>13312</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMEDTANPNEMTKDAWLNSMTPLLPDLICKGFIQDPDLKKRFDEIKMTYEQCVTLIPESTKKCQDELYASMPDKINSETAGTWGRSLGECIGKDFAEKHLIPK</AA_x0020_seq>
<AA_x0020_num>116</AA_x0020_num>
<Hydrophobicity>-0.795</Hydrophobicity>
<Aliphatics>64</Aliphatics>
<Instability>30</Instability>
<Pi>5</Pi>
</Tproteindata>
<Tproteindata>
<ID>4</ID>
<ProtName>18401</ProtName>
<EXT>17437</EXT>
<MW_x0020__x0028_Da_x0029_>13414</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMAPAYLTTHNRTGEESNAYIAGSIPSLYPTAAYSTNQVYWNLVRLACYGHTTNGQCPALIKMATNTANPIDIGYVTMDLNTGDITPKTLSAKGYSLRVIGPGEAEITKN</AA_x0020_seq>
<AA_x0020_num>123</AA_x0020_num>
<Hydrophobicity>-0.43</Hydrophobicity>
<Aliphatics>73</Aliphatics>
<Instability>21</Instability>
<Pi>6</Pi>
</Tproteindata>
<Tproteindata>
<ID>5</ID>
<ProtName>18641</ProtName>
<EXT>4533</EXT>
<MW_x0020__x0028_Da_x0029_>14905</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMAVELKTFQNIVDAIAEGKRISFVINLKKCTSEMPLNSAIVSVTPNAVMVVGDSRVTASDRHFTLDDPVARGTPMFDYSKFNLDSEGDASIKTTVLNASSYERLGSYQMNCKLGDGFKVFG</AA_x0020_seq>
<AA_x0020_num>135</AA_x0020_num>
<Hydrophobicity>-0.276</Hydrophobicity>
<Aliphatics>76</Aliphatics>
<Instability>23</Instability>
<Pi>6</Pi>
</Tproteindata>
<Tproteindata>
<ID>6</ID>
<ProtName>BSA</ProtName>
<EXT>49915</EXT>
<MW_x0020__x0028_Da_x0029_>34234</MW_x0020__x0028_Da_x0029_>
<AA_x0020_seq>MKWVTFISLLLLFSSAYSRGVFRRDTHKSEIAHRFKDLGEEHFKGLVLIAFSQYLQQCPFDEHVKLVNELTEFAKTCVADESHAGCEKSLHTLFGDELCKVASLRETYGDMADCCEKQEPERNECFLSHKDDSPDLPKLKPDPNTLCDEFKADEKKFWGKYLYEIARRHPYFYAPELLYYANKYNGVFQECCQAEDKGACLLPKIETMREKVLASSARQRLRCASIQKFGERALKAWSVARLSQKFPKAEFVEVTKLVTDLTKVHKECCHGDLLECADDRADLAKYICDNQDTISSKLKECCDKPLLEKSHCIAEVEKDAIPENLPPLTADFAEDKDVCKNYQEAKDAFLGSFLYEYSRRHPEYAVSVLLRLAKEYEATLEECCAKDDPHACYSTVFDKLKHLVDEPQNLIKQNCDQFEKLGEYGFQNALIVRYTRKVPQVSTPTLVEVSRSLGKVGTRCCTKPESERMPCTEDYLSLILNRLCVLHEKTPVSEKVTKCCTESLVNRRPCFSALTPDETYVPKAFDEKLFTFHADICTLPDTEKQIKKQTALVELLKHKPKATEEQLKTVMENFVAFVDKCCAADDKEACFAVEGPKLVVSTQTALA</AA_x0020_seq>
<AA_x0020_num>607</AA_x0020_num>
<Hydrophobicity>-0.429</Hydrophobicity>
<Aliphatics>77</Aliphatics>
<Instability>40</Instability>
<Pi>6</Pi>
</Tproteindata>
<Tproteindata>
<ID>7</ID>
<ProtName>C1QBP</ProtName>
<EXT>24325</EXT>
<MW_x0020__x0028_Da_x0029_>31776</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMLPLLRCVPRVLGSSVAGLRAAAPASPFRQLLQPAPRLCTRPFGLLSVRAGSERRPGLLRPRGPCACGCGCGSLHTDGDKAFVDFLSDEIKEERKIQKHKTLPKMSGGWELELNGTESKLVRKVAGEKITVTFNINNSIPPTFDGEEEPSQGQKVEEQEPELTSTPNFVVEVIKNDDGKKALVLDCHYPEDEVGQEDEAESDIFSIREVSFQSTGESEWKDTNYTLNTYSLDWALYDHLMDFLADRGVDNTFADELVELSTALEAPGAHYFS</AA_x0020_seq>
<AA_x0020_num>286</AA_x0020_num>
<Hydrophobicity>-0.526</Hydrophobicity>
<Aliphatics>75</Aliphatics>
<Instability>48</Instability>
<Pi>5</Pi>
</Tproteindata>
<Tproteindata>
<ID>8</ID>
<ProtName>C1QBP-GST</ProtName>
<EXT>22460</EXT>
<MW_x0020__x0028_Da_x0029_>31362</MW_x0020__x0028_Da_x0029_>
<Plasmid>pANT7_cGST</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MLPLLRCVPRVLGSSVAGLRAAAPASPFRQLLQPAPRLCTRPFGLLSVRAGSERRPGLLRPRGPCACGCGCGSLHTDGDKAFVDFLSDEIKEERKIQKHKTLPKMSGGWELELNGTEAKLVRKVAGEKITVTFNINNSIPPTFDGEEEPSQGQKVEEQEPELTSTPNFVVEVIKNDDGKKALVLDCHYPEDEVGQEDEAESDIFSIREVSFQSTGESEWKDTNYTLNTDSLDWALYDHLMDFLADRGVDNTFADELVELSTALEHQEYITFLEDLKSFVKSQ</AA_x0020_seq>
<AA_x0020_num>282</AA_x0020_num>
<Hydrophobicity>-0.461</Hydrophobicity>
<Aliphatics>80</Aliphatics>
<Instability>49</Instability>
<Pi>5</Pi>
</Tproteindata>
<Tproteindata>
<ID>9</ID>
<ProtName>ChiA_Full</ProtName>
<EXT>100325</EXT>
<MW_x0020__x0028_Da_x0029_>82603</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMNTSLKPSIAQPTACVNSLFTATGNQHWKSIVLKLTNNCNQAVDFQNSTVSFQTTAALNTSFWGDFSPLSYPDNALNISSQPQSGGNYLATLNLHFPSYPGANSKLPVGSSISIKYGAVTDSHIEGTANVYLSTTVESGSIQLINAAAKPTNVSQGYALVHVTMNGQSVSDVQLPWETSKTLSGFAAGNYAISAETVTDSNGNLYLGQANPSMVNVIANQTTSSTINYARVQETGKIKIHVQNLPGELSNYNENPTVLITQSQSGNSRSQHAVWGNTTTVAELKEGSSYQFSTPAIQYNDYNCWPTFTPSSLVASAANVPTTNLTYQCAQIVKDNVTINVSGAPSSLASLKIILTPNDGSQTVEQTIDLANGVGSSAISLTDGVIYTLSSEGVPGYTVQFSPQPLTATENATVNITLSPVTAAKGRIIGYVPGWKTPPAAQELASAGYTHVMIAFGVFSTNTPGVIVPAFETITKEYIQSLHQAGIKVILSLGGALTSIPNTTVDFHQVLVASSSPEAFKQTFINSLKELISQYGFDGFDTDIEHGINASGSFSQPQGDIAVLASIINTMYSQNSSLLITLTPQVANIAATSGFDQTWGNYASLIMQTHQSLAWVGIQLYNTGCAFGIDQVCYGPTPTDTPDFSVAMATDLLENWPATVNGRPTGFQPYISYLRPSQIVIGYPSPNASGGSDGSPVTPTTTIKRAIQCLKTAIAGNTSCGVYVPPRAYGNIGGVFNWEVTYDKNNQFKFAKELKNCAINGVCE</AA_x0020_seq>
<AA_x0020_num>777</AA_x0020_num>
<Hydrophobicity>-0.106</Hydrophobicity>
<Aliphatics>82</Aliphatics>
<Instability>30</Instability>
<Pi>5</Pi>
</Tproteindata>
<Tproteindata>
<ID>10</ID>
<ProtName>ChiA_N1</ProtName>
<EXT>18450</EXT>
<MW_x0020__x0028_Da_x0029_>16664</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMNTSLKPSIAQPTACVNSLFTATGNQHWKSIVLKLTNNCNQAVDFQNSTVSFQTTAALNTSFWGDFSPLSYPDNALNISSQPQSGGNYLATLNLHFPSYPGANSKLPVGSSISIKYGAVTDSHIEGTANVYLSTTVESGSI</AA_x0020_seq>
<AA_x0020_num>155</AA_x0020_num>
<Hydrophobicity>-0.322</Hydrophobicity>
<Aliphatics>72</Aliphatics>
<Instability>29</Instability>
<Pi>6</Pi>
</Tproteindata>
<Tproteindata>
<ID>11</ID>
<ProtName>ChiA_N2</ProtName>
<EXT>12950</EXT>
<MW_x0020__x0028_Da_x0029_>14547</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMGSIQLINAAAKPTNVSQGYALVHVTMNGQSVSDVQLPWETSKTLSGFAAGNYAISAETVTDSNGNLYLGQANPSMVNVIANQTTSSTINYARVQETGKIKIHVQNLPGELSNYNENPTVLITQSQSGNSRSQHAVWGNTTTVAELKEGSSYQFSTPAIQYND</AA_x0020_seq>
<AA_x0020_num>177</AA_x0020_num>
<Hydrophobicity>-0.505</Hydrophobicity>
<Aliphatics>73</Aliphatics>
<Instability>25</Instability>
<Pi>6</Pi>
</Tproteindata>
<Tproteindata>
<ID>12</ID>
<ProtName>ChiA_N3</ProtName>
<EXT>14440</EXT>
<MW_x0020__x0028_Da_x0029_>15699</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMGSSYQFSTPAIQYNDYNCWPTFTPSSLVASAANVPTTNLTYQCAQIVKDNVTINVSGAPSSLASLKIILTPNDGSQTVEQTIDLANGVGSSAISLTDGVIYTLSSEGVPGYTVQFSPQPLTATENATVNITLS</AA_x0020_seq>
<AA_x0020_num>148</AA_x0020_num>
<Hydrophobicity>-0.141</Hydrophobicity>
<Aliphatics>82</Aliphatics>
<Instability>33</Instability>
<Pi>5</Pi>
</Tproteindata>
<Tproteindata>
<ID>13</ID>
<ProtName>LapA</ProtName>
<EXT>54110</EXT>
<MW_x0020__x0028_Da_x0029_>44146</MW_x0020__x0028_Da_x0029_>
</Tproteindata>
<Tproteindata>
<ID>14</ID>
<ProtName>LapA_dN</ProtName>
<EXT>7575</EXT>
<MW_x0020__x0028_Da_x0029_>12992</MW_x0020__x0028_Da_x0029_>
</Tproteindata>
<Tproteindata>
<ID>15</ID>
<ProtName>LapB</ProtName>
<EXT>49070</EXT>
<MW_x0020__x0028_Da_x0029_>43984</MW_x0020__x0028_Da_x0029_>
</Tproteindata>
<Tproteindata>
<ID>16</ID>
<ProtName>LCL full</ProtName>
<EXT>40450</EXT>
<MW_x0020__x0028_Da_x0029_>56423</MW_x0020__x0028_Da_x0029_>
<Plasmid>pET-46</Plasmid>
<Plasmid_x0020_Resistance>AMP</Plasmid_x0020_Resistance>
<AA_x0020_seq>MAHHHHHHVDDDDKMKSNPASQAYVDGKVSELKNELTNKINSIPSGPQGPRGDKGEAGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPQGLPGPKGDKGEAGPQGLPGPKGDKGEAGPQGLPGPKGDKGEAGAVGPQGMPGPKGDKEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDRGEAGPQGLPGPKGDKGETGAVGPQGMPGPKGEAGDDGQGVPAGGETGQVLAKSNDLDFNTMWVDPANSGIRRQLGDKALGGTVIYVNALGTHGLVVANSDQVNSNTWWDAQDSITNPAHFDNEGKLYSDWRLPTRFELNLIYMMRNELGNFLAGNYWSSIEKSSANSWVFNSKTGEIKDIAKSKTAAVRAVRAF</AA_x0020_seq>
<AA_x0020_num>565</AA_x0020_num>
<Hydrophobicity>-1.042</Hydrophobicity>
<Aliphatics>46</Aliphatics>
<Instability>16</Instability>
<Pi>6</Pi>
</Tproteindata>
<Tproteindata>
<ID>17</ID>
<ProtName>Lcl-C</ProtName>
<EXT>38960</EXT>
