=== theoportlock/proteintools/database/Tpurificationlog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Tpurificationlog" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Tpurificationlog">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Cell disruption ID" index-key="Cell_x0020_disruption_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Experiment ID" index-key="Experiment_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Grow type ID" index-key="Grow_x0020_type_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Lab Member ID" index-key="Lab_x0020_Member_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Media ID" index-key="Media_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="Protein ID" index-key="Protein_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="SDS ID" index-key="SDS_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="TcelldisruptionTpurificationlog" index-key="Cell_x0020_disruption_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="TcompetentcellsTpurificationlog" index-key="Competent_x0020_Cell_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="TexperimentsTpurificationlog" index-key="Experiment_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="TgrowtypeTpurificationlog" index-key="Grow_x0020_type_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="TmediatypeTpurificationlog" index-key="Media_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="TproteindataTpurificationlog" index-key="Protein_x0020_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADwkvPGtjy1S6BqOxNuilBtAAAAAKi4NeqUW+VAAAAAAAAAAABUAHAA
dQByAGkAZgBpAGMAYQB0AGkAbwBuAGwAbwBnAAAAAAAAAEuKKf+JNHRNkATPGBZG
IXgAAAAAllJbo5Rb5UAAAAAAAAAAAFQAZwByAG8AdwAAAAAAAACeS1F/QE1WQYjc
smhCmEvnBwAAAPCS88a2PLVLoGo7E26KUG1JAEQAAAAAAAAA8SvU/poFxU+wXGLP
zJ1e2wcAAADwkvPGtjy1S6BqOxNuilBtTABhAGIAIABNAGUAbQBiAGUAcgAgAEkA
RAAAAAAAAABagy9ycwU4SqWbYnoYTU5HBwAAAPCS88a2PLVLoGo7E26KUG1FAHgA
cABlAHIAaQBtAGUAbgB0ACAASQBEAAAAAAAAAKnkNNZ3i21LhdRR4luW4CcHAAAA
8JLzxrY8tUugajsTbopQbVAAcgBvAHQAZQBpAG4AIABJAEQAAAAAAAAAJFPQ2VS+
vUqmDfS4VBy8PAcAAADwkvPGtjy1S6BqOxNuilBtQwBvAG0AcABlAHQAZQBuAHQA
IABDAGUAbABsACAASQBEAAAAAAAAAOYxHCAo49ZBgxN9oasX4JoHAAAA8JLzxrY8
tUugajsTbopQbU0AZQBkAGkAYQAgAEkARAAAAAAAAADzNdBOE9kpTpIr3ITvZeCv
BwAAAPCS88a2PLVLoGo7E26KUG1HAHIAbwB3ACAAdAB5AHAAZQAgAEkARAAAAAAA
AAAaVrQtjh3EQ5ESjXT/kGG7BwAAAPCS88a2PLVLoGo7E26KUG1DAGUAbABsACAA
ZABpAHMAcgB1AHAAdABpAG8AbgAgAEkARAAAAAAAAADfl9Nw8pK2TZ0GheyGimLN
BwAAAPCS88a2PLVLoGo7E26KUG1OAGkATgBUAEEAIABlAGwAdQB0AGkAbwBuACAA
YwBvAG4AYwAgACgAbQBnAC8AbQBsACkAAAAAAAAAXJwyfOS+4UWvwXe7u2mLgAcA
AADwkvPGtjy1S6BqOxNuilBtUwBEAFMAIABJAEQAAAAAAAAAC0biwQJyOES6SOf0
e9NNbQcAAADwkvPGtjy1S6BqOxNuilBtRwBGACAAZQBsAHUAdABpAG8AbgAgAGMA
bwBuAGMAIAAoAG0AZwAvAG0AbAApAAAAAAAAAIi+mxb2xvhKoW7odyWgI+cHAAAA
8JLzxrY8tUugajsTbopQbUMAbwBtAG0AZQBuAHQAcwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="8JLzxrY8tUugajsTbopQbQ==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="SubdatasheetName" type="10" value="Table.Tgrow"/>
<od:tableProperty name="LinkChildFields" type="10" value="Purification Log ID"/>
<od:tableProperty name="LinkMasterFields" type="10" value="ID"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="nktRf0BNVkGI3LJoQphL5w==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Lab_x0020_Member_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="8SvU/poFxU+wXGLPzJ1e2w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Experiment_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="WoMvcnMFOEqlm2J6GE1ORw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Protein_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="qeQ01neLbUuF1FHiW5bgJw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Competent_x0020_Cell_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="JFPQ2VS+vUqmDfS4VBy8PA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Media_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="5jEcICjj1kGDE32hqxfgmg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Grow_x0020_type_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="8zXQThPZKU6SK9yE72Xgrw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1890"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Cell_x0020_disruption_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Gla0LY4dxEOREo10/5Bhuw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="35fTcPKStk2dBoXshopizQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="SDS_x0020_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="XJwyfOS+4UWvwXe7u2mLgA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="C0biwQJyOES6SOf0e9NNbQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1260"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Comments" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="iL6bFvbG+Eqhbuh3JaAj5w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== theoportlock/proteintools/database/Tpurificationlog.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Tpurificationlog.xsd" generated="2020-01-12T15:44:39">
<Tpurificationlog>
<ID>3</ID>
<Lab_x0020_Member_x0020_ID>2</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>1</Experiment_x0020_ID>
<Protein_x0020_ID>17</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>2</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>2</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>1</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>1</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>1</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>this one changed</Comments>
</Tpurificationlog>
<Tpurificationlog>
<ID>6</ID>
<Lab_x0020_Member_x0020_ID>2</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>1</Experiment_x0020_ID>
<Protein_x0020_ID>11</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>2</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>3</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>1</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>2</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>1</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>2</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>second one</Comments>
</Tpurificationlog>
<Tpurificationlog>
<ID>7</ID>
<Lab_x0020_Member_x0020_ID>2</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>1</Experiment_x0020_ID>
<Protein_x0020_ID>1</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>2</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>2</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>2</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>2</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>4</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>4</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>6</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>lskdj</Comments>
</Tpurificationlog>
<Tpurificationlog>
<ID>11</ID>
<Lab_x0020_Member_x0020_ID>1</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>2</Experiment_x0020_ID>
<Protein_x0020_ID>2</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>1</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>2</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>2</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>1</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>1</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>1</Comments>
</Tpurificationlog>
<Tpurificationlog>
<ID>12</ID>
<Lab_x0020_Member_x0020_ID>1</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>1</Experiment_x0020_ID>
<Protein_x0020_ID>2</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>2</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>2</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>1</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>1</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>1</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>no wayâ€¦</Comments>
</Tpurificationlog>
<Tpurificationlog>
<ID>13</ID>
<Lab_x0020_Member_x0020_ID>1</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>3</Experiment_x0020_ID>
<Protein_x0020_ID>12</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>2</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>2</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>1</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>1</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>21</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>1</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>sdf</Comments>
</Tpurificationlog>
<Tpurificationlog>
<ID>14</ID>
<Lab_x0020_Member_x0020_ID>1</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>1</Experiment_x0020_ID>
<Protein_x0020_ID>2</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>1</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>2</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>2</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>1</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>1</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>1</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>1</Comments>
</Tpurificationlog>
<Tpurificationlog>
<ID>32</ID>
<Lab_x0020_Member_x0020_ID>0</Lab_x0020_Member_x0020_ID>
<Experiment_x0020_ID>2</Experiment_x0020_ID>
<Protein_x0020_ID>11</Protein_x0020_ID>
<Competent_x0020_Cell_x0020_ID>2</Competent_x0020_Cell_x0020_ID>
<Media_x0020_ID>1</Media_x0020_ID>
<Grow_x0020_type_x0020_ID>1</Grow_x0020_type_x0020_ID>
<Cell_x0020_disruption_x0020_ID>2</Cell_x0020_disruption_x0020_ID>
<NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>25</NiNTA_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<SDS_x0020_ID>2</SDS_x0020_ID>
<GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>21</GF_x0020_elution_x0020_conc_x0020__x0028_mg_x002F_ml_x0029_>
<Comments>another test</Comments>
</Tpurificationlog>
</dataroot>
